language: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

env:
  matrix:
    - LABEL=ant        CMD="ant dist test.dist" INSTALL="/bin/true"
    - LABEL=ant_no_aop CMD="ant -f build/no_aop/build.xml dist test.dist" INSTALL="ant no_aop"
    - LABEL=mvn        CMD="mvn verify --fail-at-end -Dsource.skip=true -Dmaven.javadoc.skip=true" INSTALL="mvn dependency:go-offline install clean --fail-never --quiet -DskipTests=true -Dsource.skip=true -Dmaven.javadoc.skip=true"

install:
  - ${INSTALL}

script:
  - ${CMD}

notifications:
  email:
    recipients:
      - google-guice-dev+ci@googlegroups.com

secure: "AaBXi4nqMo5xxFXJ9tC7zd3U1vmnb+dzooFcMFFc5uFT2dKnGyjXw3jmpLABHks54vOWsGssSeBbi1+e9k/bkRkDTswiyWX7omfgQc8stITZNbIVkP5MuoFeGntNuV+5oSTU2ZmvBM5bZGHxWNqxgBXXgb+9A2/UOJja7D33xCU="

after_success:
  - ./generate-latest-docs.sh

branches:
  only:
    - master
