language: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

env:
  matrix:
    - LABEL=ant        CMD="ant dist test.dist" INSTALL="/bin/true"
    - LABEL=ant_no_aop CMD="ant -f build/no_aop/build.xml dist test.dist" INSTALL="ant no_aop"
    - LABEL=mvn        CMD="mvn verify --fail-at-end -Dsource.skip=true -Dmaven.javadoc.skip=true" INSTALL="mvn dependency:go-offline install clean --fail-never --quiet -DskipTests=true -Dsource.skip=true -Dmaven.javadoc.skip=true"

install:
  - ${INSTALL}

script:
  - ${CMD}

notifications:
  email:
    recipients:
      - google-guice-dev+ci@googlegroups.com

secure: "fiX80bwvhhtfngYi8F2Z6D9Umbpcmmws0uZK8/Y/2eR7GOOh8qffqeA7vtqsnZJEMy1F6Hpls1BKmOwJCiNFLnBWkkJ8noCd2xK23cZSd63ZKCSis9jVdeiRh+0Cn/8ksouc571Kfp6XgSjW/cKdVlw4NYaIaEsWyovsAwTqO7A="
 
after_success:
  - ./generate-latest-docs.sh

branches:
  only:
    - master
